**What is NumPy?**

NumPy = Numerical Python

It is a Python library used to:

Work with numbers

Handle large data fast

Perform math, stats, matrices

Used in AI, ML, Data Science, Finance

In [66]:
a = [1,2,3]
b = [4,5,6]

here we want to add the element of a with element of b

In [67]:
print(a+b) #this is not math edition in list, its just join the two list

[1, 2, 3, 4, 5, 6]


NumPy Solution

NumPy allows real mathematical operations.

In [68]:
# !pip install numpy


In [69]:
import numpy as np

In [70]:
np.__version__


'2.3.5'

**What is a NumPy Array?**

Fixed-size

Same data type

Stored in continuous memory

Much faster than lists

In [71]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [72]:
type(arr)

numpy.ndarray

In [73]:
arr + 10

# NumPy adds 10 to each element

# This is called vectorization

# No loops needed


array([11, 12, 13, 14, 15])

**Array Properties**

In [74]:
arr.ndim


1

In [75]:
arr.shape
#5 elements in 1 dimension

(5,)

In [76]:
arr.size



5

In [77]:
arr.dtype


dtype('int64')

**Creating Special Arrays**

In [78]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [79]:
np.ones(4)


array([1., 1., 1., 1.])

In [80]:
np.full(5, 10)
#this will print 10 at 5 times


array([10, 10, 10, 10, 10])

In [81]:
#range of array
np.arange(1, 10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

 **Even Spacing**

In [82]:
np.linspace(0, 10, 5)
#Used in graphs, simulations


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Create 2D Array**

In [83]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])

In [84]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [85]:
arr2d.ndim


2

In [86]:
arr2d.shape
#2 rows, 3 columns


(2, 3)

**Indexing & Slicing**

In [87]:
arr = np.array([10, 20, 30, 40])

arr[0]


np.int64(10)

In [88]:
arr[-1]


np.int64(40)

In [89]:
arr[-2]

np.int64(30)

In [90]:
#slicing
arr[1:3]


array([20, 30])

In [91]:
arr2d[0, 1]


np.int64(2)

In [92]:
arr2d[1, 1]


np.int64(5)

In [93]:
arr2d[:, 1]


array([2, 5])

**Why NumPy is FAST**

In [94]:
#without numPy
result = []
for i in arr:
    result.append(i * 2)


In [95]:
#with numPy
arr * 2


array([20, 40, 60, 80])

***practice question***

add 10% tax in random price

In [96]:
price = np.array([100, 200, 300, 400])

# add 10% tax
final_price = price * 1.10
print(final_price)

[110. 220. 330. 440.]


***What is Broadcasting?***

Broadcasting allows NumPy to:

Perform operations on different-shaped arrays

Without writing loops

Automatically expand smaller arrays


In [97]:
#without broadcasting
a = np.array([1, 2, 3])
b = np.array([10, 20])

#a + b   # ERROR


In [98]:
a = np.array([1, 2, 3])
b = 10

a + b


array([11, 12, 13])

In [99]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr + 10


array([[11, 12, 13],
       [14, 15, 16]])

**Mathematical Operations**

In [100]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

a + b
a - b
a * b
a / b

#Every operation happens index by index


array([5., 5., 6.])

In [101]:
np.sqrt(a)
np.power(a, 2)


array([100, 400, 900])

In [102]:
np.log(a)
np.exp(a)


array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13])

***Aggregation Functions (Stats)***

In [103]:
#sum
arr = np.array([10,20,30,40])
np.sum(arr)

np.int64(100)

In [104]:
#Mean (Average)
np.mean(arr)

np.float64(25.0)

In [105]:
#Min / Max
np.min(arr)


np.int64(10)

In [106]:
np.max(arr)

np.int64(40)

In [107]:
#Standard Deviation
np.std(arr)


np.float64(11.180339887498949)

**2D Aggregation**

In [108]:
data = np.array([
    [100, 200, 300],
    [400, 500, 600]
])

np.sum(data, axis=0)   # column-wise



array([500, 700, 900])

In [109]:
np.sum(data, axis=1)   # row-wise

array([ 600, 1500])

**Shape Manipulation**

In [110]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

***Flatten vs Ravel***

In [111]:
arr2d = np.array([[1,2,3],[4,5,6]])

arr2d.flatten()



array([1, 2, 3, 4, 5, 6])

***Difference:***

flatten() → copy

ravel() → view (faster)

In [112]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 6])

***Boolean Indexing***

In [113]:
arr = np.array([10, 50, 200, 30, 400])

arr[arr > 50]


array([200, 400])

In [114]:
#multiple conditions
arr[(arr > 50) & (arr < 300)]


array([200])

***Sorting & Searching***

In [115]:
arr = np.array([4,2,3,5,7,1,6,8,9])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# Condition Locator
np.where(arr > 25)

(array([], dtype=int64),)

***Random Numbers***

In [117]:
rng = np.random.default_rng(seed=42)

rng.integers(1, 100, size=10)


array([ 9, 77, 65, 44, 43, 86,  9, 70, 20, 10])

In [118]:
#rng.normal(50, 10, size=10)

rng.normal(50, 10, size = 10)

array([36.97820493, 51.27840403, 46.83757408, 49.83198842, 41.46956072,
       58.79397975, 57.77791935, 50.66030698, 61.27241207, 54.67509342])

***Stacking & Splitting***

In [119]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))



array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

**split**

In [121]:
arr = np.array([10, 20, 30, 40, 50, 60])

np.split(arr, 3)


[array([10, 20]), array([30, 40]), array([50, 60])]

In [122]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

np.split(arr, 3)

#modular shoud be zero from the splitting digit


[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

***Linear Algebra***

**Matrix Multiplication**

In [123]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A @ B


array([[19, 22],
       [43, 50]])

**Inverse**

In [124]:
np.linalg.inv(A)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Determinant**

In [125]:
np.linalg.det(A)


np.float64(-2.0000000000000004)

***Files with NumPy***

In [126]:
#Save Array
np.save("data.npy", arr)


In [127]:
#Load Array
loaded = np.load("data.npy")


***Views vs Copies***

In [128]:
a = np.array([1, 2, 3, 4])
b = a[1:3]

b[0] = 100
print(a)


[  1 100   3   4]


In [129]:
b = a[1:3].copy()


revision is done
